/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OMSpack;

/**
 *
 * @author hevongordon
 */
import java.sql.*;
import java.io.*;
public class reportForm extends javax.swing.JFrame {
Connection OMSconn=null;
    /**
     * Creates new form reportForm
     */
    public reportForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        perpDesc = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        caseStatus = new javax.swing.JTextField();
        caseNum = new javax.swing.JTextField();
        reportingOfficer = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        crimeDesc = new javax.swing.JTextField();
        perpAlias = new javax.swing.JTextField();
        filePath = new javax.swing.JTextField();
        generate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        date.setBorder(null);
        date.setOpaque(false);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 216, 130, -1));

        time.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        time.setBorder(null);
        time.setOpaque(false);
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 311, 180, 15));

        perpDesc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        perpDesc.setBorder(null);
        perpDesc.setOpaque(false);
        getContentPane().add(perpDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 380, 30));

        type.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        type.setBorder(null);
        type.setOpaque(false);
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 239, 230, 15));

        caseStatus.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        caseStatus.setBorder(null);
        caseStatus.setOpaque(false);
        getContentPane().add(caseStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 474, 240, 12));

        caseNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caseNum.setBorder(null);
        caseNum.setOpaque(false);
        getContentPane().add(caseNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 497, 250, 15));

        reportingOfficer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        reportingOfficer.setBorder(null);
        reportingOfficer.setOpaque(false);
        getContentPane().add(reportingOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 263, 250, 15));

        location.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        location.setBorder(null);
        location.setOpaque(false);
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 288, 370, 15));

        crimeDesc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crimeDesc.setBorder(null);
        crimeDesc.setOpaque(false);
        getContentPane().add(crimeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 350, 380, 40));

        perpAlias.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        perpAlias.setBorder(null);
        perpAlias.setOpaque(false);
        getContentPane().add(perpAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 448, 240, 15));
        getContentPane().add(filePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 140, -1));

        generate.setText("Generate");
        generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateMouseClicked(evt);
            }
        });
        getContentPane().add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 493, -1, -1));

        jLabel1.setText("Path to image:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, 20));

        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 160, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OMSpack/OMSReport.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
      
        try {
         
           FileWriter writes=new FileWriter("C:/Users/hevongordon/Desktop/OMSdata/reportFile.txt",true);
           BufferedWriter writer = new BufferedWriter(writes);
            writer.write("\r"+"\n"+"\r"+"-------NEW REPORT------"+"\r"+"\n"+"\r"+"Date"+": "+date.getText()+"\r"+"\n"+"Type of offense"+": "+type.getText()+"\r"+"\n"+"Officer in charge"+": "+reportingOfficer.getText()+"\r"+"\n"+"Location of crime"+": "+location.getText()+"\r"+"\n"+
              "Time Reported"+": "+time.getText()+"\r"+"\n"+"short description of crime"+": "+crimeDesc.getText()+"\r"+"\n"+"short description of perp"+": "+
                    perpDesc.getText()+"\r"+"\n"+"Alias of offender"+": "+perpAlias.getText()+"\r"+"\n"+"Case status"+": "+caseStatus.getText()+"\r"+"\n"+"Case Number" + ": " +caseNum.getText()+"\r"+"\n"+"Path to file:"
                    +filePath.getText());
            writer.close();
            
        } catch ( IOException e ) {
          System.out.print (e.getMessage());
        }
    }//GEN-LAST:event_submitMouseClicked

    private void generateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseClicked
        int max=999999999;
        int min=10000000;
       int randomm=1 + (int)(Math.random() * ((max - min) + 1));
       String setter=String.valueOf(randomm);
        caseNum.setText(setter);
    }//GEN-LAST:event_generateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField caseNum;
    private javax.swing.JTextField caseStatus;
    private javax.swing.JTextField crimeDesc;
    private javax.swing.JTextField date;
    private javax.swing.JTextField filePath;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField perpAlias;
    private javax.swing.JTextField perpDesc;
    private javax.swing.JTextField reportingOfficer;
    private javax.swing.JLabel submit;
    private javax.swing.JTextField time;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
